name: GPT Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  gpt-review:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: gpt-3.5-turbo
          LANGUAGE: Korean
          PROMPT: |
            Java + Spring Boot 코드를 기준으로 리뷰해주세요.
            - 서비스/컨트롤러 역할 분리 여부
            - 유효성 검사 및 예외 처리 위치
            - 불필요한 코드/주석
            - 컨벤션은 무시하고 로직 중심으로 리뷰
